#!/usr/bin/ruby
#
# This file is part of CPEE-LOGGING-XES-YAML.
#
# CPEE-LOGGING-XES-YAML is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# CPEE-LOGGING-XES-YAML is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for
# more details.
#
# You should have received a copy of the GNU Lesser General Public License along with
# CPEE-LOGGING-XES-YAML (file LICENSE in the main directory).  If not, see
# <http://www.gnu.org/licenses/>.

require 'rubygems'
require 'cpee-logging-xes-yaml/logging'

options = {
  :host => 'localhost',
  :port => 9299,
  :secure => false
}

Riddl::Server.new(CPEE::Logging::SERVER, options) do
  accessible_description true
  cross_site_xhr true

  @riddl_opts[:log_dir] ||= File.join(__dir__,'logs')
  @riddl_opts[:subscriptions_dir] ||= File.join(__dir__,'subscriptions')

  use CPEE::Logging::implementation(@riddl_opts)
end.loop!
