#!/usr/bin/ruby
#
# This file is part of CPEE-LOGGING-XES-YAML.
#
# CPEE-LOGGING-XES-YAML is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# CPEE-LOGGING-XES-YAML is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for
# more details.
#
# You should have received a copy of the GNU Lesser General Public License along with
# CPEE-LOGGING-XES-YAML (file LICENSE in the main directory).  If not, see
# <http://www.gnu.org/licenses/>.

path = ARGV.shift()
lookup_lines = ARGV.shift().to_i()
regexes = ARGV
regexes.map!() { |el| el.gsub("\\n","\n") }

dir = Dir.open(File.join(path))
children = dir.children()
#pp children.length()
#pp children.filter() { |el| el.include?('.xes.yaml') }.length()
#pp children.filter() { |el| el.include?('.xes.shift.yaml') }.length()
#pp children.filter() { |el| el.include?('data.json') }.length()
#pp children.filter() { |el| el.include?('.anno') }.length()
#pp children.filter() { |el| el.include?('.probe') }.length()
#pp children.filter() { |el| el.include?('.branches.json') }.length()
#pp children.filter() { |el| el.include?('.shift.json') }.length()
children.filter!() { |el| el.end_with?('.xes.yaml') }
children.each() { |filename|
  begin
    file = File.open(File.join(path,filename))
    lookup_lines.times() {
      line = file.readline()
      regexes.each() { |regex|
        #pp regex
        if(line.include?(regex)) then
          puts "#{filename} matches '#{regex.gsub("\n","\\n")}' in line '#{line.gsub("\n","\\n")}' (file last modified: #{file.stat().mtime()})"                                             
          break
        end
      }
    }
  rescue Exception => e
    #pp "Problem opening or reading file: #{e} -> go to next file"
    #pp filename
    next
  ensure
    file.close()
  end
}
dir.close()
